### PR TITLE
Various location fixes

### LINKED ISSUE #589: YARP fails to deserialize truffleruby/core/argf.rb
This file: https://github.com/oracle/truffleruby/blob/795871285cf35855382b66a039da33d981068dbc/src/main/ruby/truffleruby/core/argf.rb

Note that YARP.parse does not raise, and YARP.dump does produce something, but it's the loading that fails.

```
$ ruby -I../../yarp/lib -ryarp -e 'Dir.glob("src/main/ruby/truffleruby/core/argf.rb") { |file| puts file; source=File.read(file); p YARP.load source, YARP.dump(source) }'
src/main/ruby/truffleruby/core/argf.rb
/home/eregon/code/yarp/lib/yarp/serialize.rb:200:in `load_token': undefined method `force_encoding' for nil:NilClass (NoMethodError)

        Token.new(type, range.force_encoding(encoding), location)
                             ^^^^^^^^^^^^^^^
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:283:in `load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `block in load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `times'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `each'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `map'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:253:in `load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `block in load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `times'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `each'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `map'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:289:in `load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `block in load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `times'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `each'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `map'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:322:in `load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:303:in `load_node'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:28:in `load'
	from /home/eregon/code/yarp/lib/yarp/serialize.rb:13:in `load'
	from /home/eregon/code/yarp/lib/yarp.rb:177:in `load'
	from -e:1:in `block in <main>'
	from <internal:dir>:220:in `glob'
	from -e:1:in `<main>'
```

And the Java Loader also fails:
```
Index 197 out of bounds for length 156 (java.lang.ArrayIndexOutOfBoundsException)
	from org.yarp.Loader.loadToken(Loader.java:81)
	from org.yarp.Loader.loadTokens(Loader.java:62)
	from org.yarp.Loader.loadNode(Loader.java:264)
	from org.yarp.Loader.loadNodes(Loader.java:71)
	from org.yarp.Loader.loadNode(Loader.java:278)
	from org.yarp.Loader.loadNode(Loader.java:140)
	from org.yarp.Loader.loadNodes(Loader.java:71)
	from org.yarp.Loader.loadNode(Loader.java:278)
	from org.yarp.Loader.loadNode(Loader.java:212)
	from org.yarp.Loader.loadNodes(Loader.java:71)
	from org.yarp.Loader.loadNode(Loader.java:278)
	from org.yarp.Loader.loadNode(Loader.java:240)
	from org.yarp.Loader.load(Loader.java:30)
	from org.yarp.Loader.load(Loader.java:11)
	from org.truffleruby.debug.TruffleDebugNodes$YARPExecuteNode.yarpExecute(TruffleDebugNodes.java:289)
	from org.truffleruby.debug.TruffleDebugNodesFactory$YARPExecuteNodeFactory$YARPExecuteNodeGen.executeAndSpecialize(TruffleDebugNodesFactory.java:1236)
	from org.truffleruby.debug.TruffleDebugNodesFactory$YARPExecuteNodeFactory$YARPExecuteNodeGen.execute(TruffleDebugNodesFactory.java:1199)
	from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:58)
-e:1:in `yarp_execute'
	from -e:1:in `block in <main>'
	from <internal:core> core/dir.rb:291:in `each'
	from <internal:core> core/dir.rb:291:in `glob'
	from -e:1:in `<main>'
```

### PR DESCRIPTION
**Pull request by kddnewton**
* Optional locations now store `NULL` in their start and end to indicate that they were not provided.
* When they are serialized, they always serialize a single byte to indicate whether or not they are present.
* The deserializers now always read at least one byte to determine if they are present, and then read the location if it's non-zero.

Fixes #589.

### CODE REVIEW

File: bin/templates/ext/yarp/node.c.erb [hunk 1]
```diff
@@ -11,9 +11,7 @@ extern VALUE rb_cYARPLocation;
 
 static VALUE
 location_new(yp_parser_t *parser, const char *start, const char *end) {
-  VALUE real_start = start ? LONG2FIX(start - parser->start) : Qnil;
-  VALUE real_end = end ? LONG2FIX(end - parser->start) : Qnil;
-  VALUE argv[] = { real_start, real_end };
+  VALUE argv[] = { LONG2FIX(start - parser->start), LONG2FIX(end - parser->start) };
```
Comment (eregon) [inline bin/templates/ext/yarp/node.c.erb:14]: It would be good to `assert(start); assert(end);` here to make sure we don't pass the value of `-parser->start` as an "offset" to Ruby, like done in https://github.com/Shopify/yarp/blob/e2972023e6b7d06de7caaec6f3858e697a988a1b/bin/templates/src/serialize.c.erb#L22-L23

**Comment by eregon** [comment]
As discussed on Slack this is also an issue for optional nodes. And maybe for optional tokens (not if EOF Token can never be the value of an optional token field, but can we guarantee that)?.

**Comment by kddnewton** [comment]
Yeah may as well do tokens as well. https://github.com/Shopify/yarp/issues/665
