### PR TITLE
Fix parsing method calls with constant paths

### LINKED ISSUE #479: Constants and local reads can have blocks and become calls
```ruby
foo = 1
foo do
end
```

```ruby
Const do
end
```

### LINKED ISSUE #496: Constant paths can be method calls
```ruby
Bundler::URI uri
```

### PR DESCRIPTION
**Pull request by haldun**
Fixes #496
Fixes #479

### CODE REVIEW

File: test/parse_test.rb [hunk 1]
```diff
@@ -2053,6 +2053,23 @@ def a(b:
     assert_parses expected, "foo(\n:a,\nb: :c,\n)"
   end
 
+  test "method call with constant paths" do
+    expected = CallNode(
+      ConstantReadNode(CONSTANT("Bundler")),
+      COLON_COLON("::"),
+      IDENTIFIER("uri"),
```
Comment (kddnewton) [inline test/parse_test.rb:2060]: This token seems wrong. It should be `CONSTANT("URI")` not the identifier. I think something may have gotten messed up here.

**Review by kddnewton — CHANGES_REQUESTED** [review]
